config/routes.rb
Rails.application.routes.draw do
  post '/vote' => 'polls#vote', as: :vote
  root "polls#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/poll.rb
class Poll < ApplicationRecord
  has_many :poll_options
end

app/models/poll_option.rb
class PollOption < ApplicationRecord
  belongs_to :poll
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

  def index 
    @poll = Poll.where(finished_at: nil).last
    @poll_options = @poll.poll_options.order :name
  end

  def vote 
    @poll_option = PollOption.find params[:poll_option_id]
    @poll_option.increment! :votes

    respond_to do |format|
      format.turbo_stream { render :vote }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Votação quem deve ser eliminado?</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container max-w-screen-sm mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/polls/_poll.html.erb
<div id="poll-container">
    <h1 class="text-4xl font-bold mb-10">
      Vote for the best programming language below: 
      <%= @poll_options.pluck(:name).to_sentence last_word_connector: ' ou ' %>?
    </h1>

    <div class="flex flex-col gap-4 w-100">
      <% @poll_options.each do |option| %>
        <%= button_to vote_url, 
          method: :post, 
          class: 'flex-grow flex options-center border border-gray-600 p-4 text-left', 
          form_class: 'flex w-100', 
          params: { poll_option_id: option.id } do %>
          <h2 class="text-2xl font-bold text-slate-800 flex-grow"><%= option.name %></h2>
          <%= image_tag option.photo, class: 'h-16 w-16 object-contain', alt: '' %>
        <% end %>
      <% end %>
    </div>
</div>

app/views/polls/index.html.erb
<%= render 'poll' %>

app/views/polls/vote.turbo_stream.erb
<%= turbo_stream.replace 'poll-container' do %>
    <div id="poll-container">
      <div class="flex items-center p-4 mb-8">
        <div class="flex-grow">
          <p class="font-semibold text-slate-700">
            YOU VOTED FOR
          </p>
          <p class="text-2xl font-bold">
            <%= @poll_option.name %>
          </p>
        </div>

        <%= image_tag @poll_option.photo, class: 'h-16 w-16 object-contain', alt: '' %>
      </div>

      <%= link_to 'Vote again', 
      root_path, 
      class: 'block text-center p-4 text-white bg-violet-800 hover:bg-violet-900'%>
    </div>
<% end %>